In [1]:
# Magic methods 
%load_ext autoreload
%aimport helpers
%autoreload 1

In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
from helpers import show_model
from pomegranate import State, HiddenMarkovModel, DiscreteDistribution 

In [12]:
# import python modules -- this cell needs to be run again if you make changes to any of the files
from IPython.core.display import HTML
from itertools import chain
from collections import Counter, defaultdict
from helpers import show_model, Dataset

In [3]:
# Creating the model
model = HiddenMarkovModel(name = "Example Model")

In [4]:
# Emission probability distribution p(umbrella | weather)
sunny_emission = DiscreteDistribution({'yes': 0.1, 'no': 0.9})
sunny_state = State(sunny_emission, "Sunny")

rainy_emission = DiscreteDistribution({'yes': 0.8, 'no': 0.2})
rainy_state = State(rainy_emission, "Rainy")

In [5]:
# Adding the emission to the model
model.add_states(sunny_state, rainy_state)

In [6]:
# Transotion probability
model.add_transition(model.start, sunny_state, 0.5)
model.add_transition(model.start, rainy_state, 0.5)

model.add_transition(sunny_state, sunny_state, 0.8)
model.add_transition(sunny_state, rainy_state, 0.2)

model.add_transition(rainy_state, sunny_state, 0.6)
model.add_transition(rainy_state, rainy_state, 0.4)

model.bake()

In [7]:
model.edge_count()

6

In [8]:
model.node_count()

4

In [9]:
model.states

[{
     "class" : "State",
     "distribution" : {
         "class" : "Distribution",
         "name" : "DiscreteDistribution",
         "parameters" : [
             {
                 "yes" : 0.8,
                 "no" : 0.2
             }
         ],
         "frozen" : false
     },
     "name" : "Rainy",
     "weight" : 1.0
 }, {
     "class" : "State",
     "distribution" : {
         "class" : "Distribution",
         "name" : "DiscreteDistribution",
         "parameters" : [
             {
                 "yes" : 0.1,
                 "no" : 0.9
             }
         ],
         "frozen" : false
     },
     "name" : "Sunny",
     "weight" : 1.0
 }, {
     "class" : "State",
     "distribution" : null,
     "name" : "Example Model-start",
     "weight" : 1.0
 }, {
     "class" : "State",
     "distribution" : null,
     "name" : "Example Model-end",
     "weight" : 1.0
 }]

In [10]:
model.dense_transition_matrix()

array([[0.4, 0.6, 0. , 0. ],
       [0.2, 0.8, 0. , 0. ],
       [0.5, 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0. ]])

In [27]:
column_order = ["Example Model-start", "Sunny", "Rainy", "Example Model-end"]
column_names = [s.name for s in model.states]
column_index = [column_names.index(c) for c in column_order]

In [24]:
column_names

['Rainy', 'Sunny', 'Example Model-start', 'Example Model-end']

In [25]:
column_names.index("Rainy")

0

In [28]:
column_index

[2, 1, 0, 3]

In [30]:
model.dense_transition_matrix()[:, column_index]

array([[0. , 0.6, 0.4, 0. ],
       [0. , 0.8, 0.2, 0. ],
       [0. , 0.5, 0.5, 0. ],
       [0. , 0. , 0. , 0. ]])

In [31]:
model.dense_transition_matrix()[:, column_index][column_index, :]

array([[0. , 0.5, 0.5, 0. ],
       [0. , 0.8, 0.2, 0. ],
       [0. , 0.6, 0.4, 0. ],
       [0. , 0. , 0. , 0. ]])